[project]
name = "pills_identification"
version = "0.0.1"
authors = [
    {name="KMS Healthcare"}
]
description = "Pills identification"

[tool.setuptools]
py-modules = ["pills_identification"]

[tool.black]
line-length = 120
target-version = ['py39']